## 📌 Guía de NumPy con ejemplos

#### Esta es una guia compelta de todos los comandos que hay en numpy y su uso con diferentes casos para usar correctamente esste archivo se debe importar la libreria de numpy y activar el entorno virtual de conda el cual se describe como se insstala al inicio del repositorio.

In [1]:
import numpy as np # libreria numpy

🔹 1. Creación de arrays

In [2]:
# Crear un array a partir de una lista
arr = np.array([1, 2, 3])  # array de enteros

print('lista o array:' ,arr)

# Array de ceros
zeros = np.zeros((2,3))  # 2 filas x 3 columnas llenas de 0

print('array de ceros:', zeros)

# Array de unos
ones = np.ones((3,2))  # 3x2 llenos de 1
print('array de unos:', ones)

# Array lleno con un valor específico
full = np.full((2,2), 7)  # 2x2 con todos los elementos = 7
print('array lleno con un valor específico:', full)

# Array vacío (valores no inicializados)
empty = np.empty((2,2))
print('array vacío:', empty)

# Array con rango de números
arr_range = np.arange(0,10,2)  # de 0 a 10 (excluido) con paso 2
print('array con rango de números:', arr_range)

# Array con valores espaciados linealmente
lin = np.linspace(0,1,5)  # 5 números entre 0 y 1
print('array con valores espaciados linealmente:', lin)

lista o array: [1 2 3]
array de ceros: [[0. 0. 0.]
 [0. 0. 0.]]
array de unos: [[1. 1.]
 [1. 1.]
 [1. 1.]]
array lleno con un valor específico: [[7 7]
 [7 7]]
array vacío: [[7.78775915e-319 0.00000000e+000]
 [0.00000000e+000 6.25514754e-310]]
array con rango de números: [0 2 4 6 8]
array con valores espaciados linealmente: [0.   0.25 0.5  0.75 1.  ]


🔹 2. Información o lectura de arrays

In [3]:
arr = np.array([[1,2,3],[4,5,6]])


print('Información o lectura de arrays:', arr.shape)   # forma del array (filas, columnas)
print('cantidad de elementos del array:', arr.size)    # cantidad de elementos
print('número de dimensiones del array:', arr.ndim)    # número de dimensiones
print('tipo de dato del array:', arr.dtype)    # tipo de dato
print('tamaño en bytes de cada elemento:', arr.itemsize) # tamaño en bytes de cada elemento


Información o lectura de arrays: (2, 3)
cantidad de elementos del array: 6
número de dimensiones del array: 2
tipo de dato del array: int64
tamaño en bytes de cada elemento: 8


🔹 3. Operaciones matemáticas básicas entre listas o arrays

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = []


print('suma de elementos por su orden en la lista:', np.add(a,b))        # suma elemento a elemento
print('resta los elementos dependiendo de su posicion:', np.subtract(a,b))   # resta elemento a elemento
print('producto de elementos por su orden en la lista:', np.multiply(a,b))   # multiplicación elemento a elemento
print('división elemento a elemento:', np.divide(a,b))     # división elemento a elemento
print('división elemento a elemento:', np.divide(a,b))     # división elemento a elemento
print('potencia elemento a elemento:', np.power(a,2))      # elevar al cuadrado
print('raíz cuadrada elemento a elemento:', np.sqrt(a))         # raíz cuadrada
print('exponencial elemento a elemento:', np.exp(a))          # e^a
print('logaritmo natural elemento a elemento:', np.log(a))          # logaritmo natural
print('seno coseno o tangente elemento a elemento:', np.sin(a), np.cos(a), np.tan(a))
print('seno de cada elemento:', np.sin(a))          # seno de cada elemento
print('coseno de cada elemento:', np.cos(a))          # coseno de cada elemento
print('tangente de cada elemento:', np.tan(a))          # tangente de cada elemento

c = np.add(a,b)  # suma elemento a elemento y guarda en nueva array
np.add(a,b, out=c) # de esta forma tambien se puede guardar en una nueva array
print('array guardada de una suma:')
print(c)
print(c)

suma de elementos por su orden en la lista: [5 7 9]
resta los elementos dependiendo de su posicion: [-3 -3 -3]
producto de elementos por su orden en la lista: [ 4 10 18]
división elemento a elemento: [0.25 0.4  0.5 ]
división elemento a elemento: [0.25 0.4  0.5 ]
potencia elemento a elemento: [1 4 9]
raíz cuadrada elemento a elemento: [1.         1.41421356 1.73205081]
exponencial elemento a elemento: [ 2.71828183  7.3890561  20.08553692]
logaritmo natural elemento a elemento: [0.         0.69314718 1.09861229]
seno coseno o tangente elemento a elemento: [0.84147098 0.90929743 0.14112001] [ 0.54030231 -0.41614684 -0.9899925 ] [ 1.55740772 -2.18503986 -0.14254654]
seno de cada elemento: [0.84147098 0.90929743 0.14112001]
coseno de cada elemento: [ 0.54030231 -0.41614684 -0.9899925 ]
tangente de cada elemento: [ 1.55740772 -2.18503986 -0.14254654]
array guardada de una suma:
[5 7 9]
[5 7 9]


🔹 4. Estadísticas y agregaciones

In [5]:
arr = np.array([1,2,3,4,5])

print('suma todos los elementos que esten en el array', np.sum(arr))         # suma de todos los elementos
print('promedio de todos los elementos que esten en el array', np.mean(arr))        # promedio
print('mediana de todos los elementos que esten en el array', np.median(arr))      # mediana
print('desviación estándar de todos los elementos que esten en el array', np.std(arr))         # desviación estándar
print('varianza de todos los elementos que esten en el array', np.var(arr))         # varianza
print('valor mínimo de todos los elementos que esten en el array', np.min(arr))         # valor mínimo
print('valor máximo de todos los elementos que esten en el array', np.max(arr))         # valor máximo
print('índice del valor mínimo de todos los elementos que esten en el array', np.argmin(arr))      # índice del valor mínimo
print('índice del valor máximo de todos los elementos que esten en el array', np.argmax(arr))      # índice del valor máximo


suma todos los elementos que esten en el array 15
promedio de todos los elementos que esten en el array 3.0
mediana de todos los elementos que esten en el array 3.0
desviación estándar de todos los elementos que esten en el array 1.4142135623730951
varianza de todos los elementos que esten en el array 2.0
valor mínimo de todos los elementos que esten en el array 1
valor máximo de todos los elementos que esten en el array 5
índice del valor mínimo de todos los elementos que esten en el array 0
índice del valor máximo de todos los elementos que esten en el array 4


🔹 5. Manipulación de arrays

In [6]:
arr = np.array([[1,2,3],[4,5,6]])


print('cambiar forma a 3x2:', arr.reshape((3,2)))  # cambiar forma a 3x2
print('aplanar en 1D:', arr.ravel())          # aplanar en 1D
print('aplanar en 1D (copia):', arr.flatten())        # aplanar en 1D (copia)
print('transpuesta:', arr.T)                # transpuesta
print('unir arrays verticalmente:', np.concatenate([arr, arr], axis=0))  # unir arrays verticalmente
print('apilar verticalmente:', np.vstack([arr, arr])) # apilar verticalmente
print('apilar horizontalmente:', np.hstack([arr, arr])) # apilar horizontalmente
print('dividir verticalmente en 2:', np.split(arr,2,axis=0)) # dividir verticalmente en 2
print('repetir array 2 veces verticalmente:', np.tile(arr,(2,1)))     # repetir array 2 veces verticalmente
print('repetir cada columna 2 veces:', np.repeat(arr,2,axis=1)) # repetir cada columna 2 veces
print('voltear filas:', np.flip(arr,axis=0))    # voltear filas
print('rotar columnas:', np.roll(arr,1,axis=1))  # rotar columnas
print('ordenar filas:', np.sort(arr,axis=1))    # ordenar filas

cambiar forma a 3x2: [[1 2]
 [3 4]
 [5 6]]
aplanar en 1D: [1 2 3 4 5 6]
aplanar en 1D (copia): [1 2 3 4 5 6]
transpuesta: [[1 4]
 [2 5]
 [3 6]]
unir arrays verticalmente: [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
apilar verticalmente: [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
apilar horizontalmente: [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
dividir verticalmente en 2: [array([[1, 2, 3]]), array([[4, 5, 6]])]
repetir array 2 veces verticalmente: [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
repetir cada columna 2 veces: [[1 1 2 2 3 3]
 [4 4 5 5 6 6]]
voltear filas: [[4 5 6]
 [1 2 3]]
rotar columnas: [[3 1 2]
 [6 4 5]]
ordenar filas: [[1 2 3]
 [4 5 6]]


### 🔹 6. Indexación y condiciones

In [7]:
arr = np.array([10,20,30,40,50])

print('arr[0]:', arr[0])        # primer elemento
print('arr[1:4]:', arr[1:4])      # elementos 1 a 3
print('arr[::2]:', arr[::2])      # elementos cada 2 pasos
print('np.where(arr>25):', np.where(arr>25))  # índices donde la condición es True
print('np.nonzero(arr>25):', np.nonzero(arr>25)) # lo mismo que np.where
print('arr[np.where(arr>25)]:', arr[np.where(arr>25)]) # elementos que cumplen la condición

arr[0]: 10
arr[1:4]: [20 30 40]
arr[::2]: [10 30 50]
np.where(arr>25): (array([2, 3, 4]),)
np.nonzero(arr>25): (array([2, 3, 4]),)
arr[np.where(arr>25)]: [30 40 50]


### 🔹 7. Álgebra lineal
np.linalg significa que me trqaiga el resultado como si fuera algebra lineal

In [8]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print('np.dot(A,B):', np.dot(A,B))           # producto punto
print('np.matmul(A,B):', np.matmul(A,B))        # multiplicación de matrices
print('np.cross([1,0,0],[0,1,0]):', np.cross([1,0,0],[0,1,0])) # producto cruzado
print('np.linalg.inv(A):', np.linalg.inv(A))      # matriz inversa
print('np.linalg.det(A):', np.linalg.det(A))      # determinante
print('np.linalg.eig(A):', np.linalg.eig(A))      # eigenvalores y eigenvectores
print('np.linalg.norm(A):', np.linalg.norm(A))     # norma (longitud) de la matriz

np.dot(A,B): [[19 22]
 [43 50]]
np.matmul(A,B): [[19 22]
 [43 50]]
np.cross([1,0,0],[0,1,0]): [0 0 1]
np.linalg.inv(A): [[-2.   1. ]
 [ 1.5 -0.5]]
np.linalg.det(A): -2.0000000000000004
np.linalg.eig(A): EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
np.linalg.norm(A): 5.477225575051661


🔹 8. Funciones aleatorias

In [9]:
np.random.seed(42)           # fijar semilla para reproducibilidad
print('3 numeros uniformes entre 0 y 1:', np.random.rand(3))     # 3 números uniformes entre 0 y 1
print('3 numeros normales (media=0, sd=1):', np.random.randn(3))    # 3 números normales (media=0, sd=1)
print('5 enteros aleatorios entre 0 y 9:', np.random.randint(0,10,5)) # 5 enteros aleatorios entre 0 y 9
print('elegir aleatoriamente 2 elementos:', np.random.choice([10,20,30], 2)) # elegir aleatoriamente 2 elementos
np.random.shuffle(arr)       # mezclar el array
print('permutar sin modificar original:', np.random.permutation(arr)) # permutar sin modificar original
print('5 numeros de una normal (media=0, sd=1):', np.random.normal(0,1,5))  # 5 números de una normal (media=0, sd=1)

3 numeros uniformes entre 0 y 1: [0.37454012 0.95071431 0.73199394]
3 numeros normales (media=0, sd=1): [-1.11188012  0.31890218  0.27904129]
5 enteros aleatorios entre 0 y 9: [7 2 5 4 1]
elegir aleatoriamente 2 elementos: [20 20]
permutar sin modificar original: [10 50 20 30 40]
5 numeros de una normal (media=0, sd=1): [ 1.01051528 -1.72491783 -0.56228753 -1.01283112  0.31424733]


🔹 9. Guardar y cargar dato

In [10]:
arr = np.array([1,2,3,4,5])

np.save('arr.npy', arr)        # guardar array en formato binario
loaded = np.load('arr.npy')    # cargar array esto para verificar que se guardó correctamente
print('loaded:', loaded)

np.savetxt('arr.txt', arr)     # guardar como texto para verificar que se guardó correctamente
loaded_txt = np.loadtxt('arr.txt')
print('loaded_txt:', loaded_txt)


loaded: [1 2 3 4 5]
loaded_txt: [1. 2. 3. 4. 5.]
